name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches:
      - "accept-pnh"

permissions:
  id-token: write
  contents: read

jobs:
  build_backend:
    runs-on: "ubuntu-latest"
    environment: accept-pnh
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ vars.ACR_NAME}}

      - name: Build Docker image for Backend
        run: |
          docker build -t ${{vars.ACR_NAME}}.azurecr.io/backend:${{github.ref_name}} -f ${{github.workspace}}/app/src/prod.Dockerfile .
      
      - name: Push Docker image for Backend
        run: |
          docker push ${{vars.ACR_NAME}}.azurecr.io/backend:${{github.ref_name}}
      
      - name: Deploy Backend to Azure Container App
        run: |
          az containerapp create \
            --name backend-prod-app \
            --resource-group $RESOURCE_GROUP_NAME \
            --image ${{vars.ACR_NAME}}.azurecr.io/backend:${{github.ref_name}} \
            --target-port 8000 \
            --ingress external \
            --env-vars DB_NAME=$DB_NAME \
              DB_USER=$DB_USER \
              DB_PASSWORD=${{secrets.DB_PASSWORD}} \
              DB_HOST=$DB_HOST \
              DB_PORT=$DB_PORT \
            --registry-server ${{vars.ACR_NAME}}.azurecr.io \
            --cpu 2.0 \
            --memory 4.0Gi \
            --query properties.configuration.ingress.fqdn