name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches:
      - "prod-pnh"

permissions:
  id-token: write
  contents: read

jobs:
  build_rekenkern:
    runs-on: "ubuntu-latest"
    environment: prod-pnh
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Add containerapp extension
        run: |
          az extension add --name containerapp --upgrade --allow-preview true

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{vars.ACR_NAME}}

      - name: Build Docker image for Rekenkern
        run: |
          docker build -t ${{vars.ACR_NAME}}.azurecr.io/data:${{github.ref_name}} -f ${{github.workspace}}/hail/Dockerfile ${{github.workspace}}/hail
      
      - name: Push Docker image for Rekenkern
        run: |
          docker push ${{vars.ACR_NAME}}.azurecr.io/data:${{github.ref_name}}
      
      # - name: Deploy Rekenkern to Azure Container App
      #   run: |
      #     IDENTITY_ID=$(az identity show \
      #             --name ${{vars.IDENTITY}}  \
      #             --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
      #             --query id \
      #             --output tsv)

      #     az containerapp create \
      #       --name data-prod-app \
      #       --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
      #       --environment ${{vars.CONTAINER_APPS_ENV}} \
      #       --image ${{vars.ACR_NAME}}.azurecr.io/data:${{github.ref_name}} \
      #       --target-port 7000 \
      #       --ingress external \
      #       --env-vars REDIS_HOST=${{vars.REDIS_HOST}} \
      #         REDIS_PORT=${{vars.REDIS_PORT}} \
      #         REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}} \
      #         ETM_API_KEY=${{secrets.ETM_API_KEY}} \
      #         SUPER_SECRET_KEY=${{secrets.SUPER_SECRET_KEY}} \
      #         TRUSTED_ORIGINS_DATA=${{vars.TRUSTED_ORIGINS_DATA}} \
      #       --registry-server ${{vars.ACR_NAME}}.azurecr.io \
      #       --user-assigned "$IDENTITY_ID" \
      #       --registry-identity $IDENTITY_ID \
      #       --cpu 2.0 \
      #       --memory 4.0Gi \
      #       --query properties.configuration.ingress.fqdn

      #     az containerapp ingress cors enable \
      #       --name data-prod-app \
      #       --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
      #       --allowed-origins ${{vars.TRUSTED_ORIGINS_DATA}}


  build_backend:
    runs-on: "ubuntu-latest"
    environment: prod-pnh
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ vars.ACR_NAME}}

      - name: Build Docker image for Backend
        run: |
          docker build -t ${{vars.ACR_NAME}}.azurecr.io/backend:${{github.ref_name}} -f ${{github.workspace}}/app/src/prod.Dockerfile ${{github.workspace}}/app/src
      
      - name: Push Docker image for Backend
        run: |
          docker push ${{vars.ACR_NAME}}.azurecr.io/backend:${{github.ref_name}}
      
      - name: Deploy Backend to Azure Container App
        run: |
          IDENTITY_ID=$(az identity show \
                  --name ${{vars.IDENTITY}}  \
                  --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
                  --query id \
                  --output tsv)

          az containerapp create \
            --name backend-prod-app \
            --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
            --environment ${{vars.CONTAINER_APPS_ENV}} \
            --image ${{vars.ACR_NAME}}.azurecr.io/backend:${{github.ref_name}} \
            --target-port 8000 \
            --ingress external \
            --env-vars DB_NAME=${{vars.DB_NAME}} \
              DB_USER=${{vars.DB_USER}} \
              DB_PASSWORD=${{secrets.DB_PASSWORD}} \
              DB_HOST=${{vars.DB_HOST}} \
              DB_PORT=${{vars.DB_PORT}} \
              MEDIA_PATH=/app/media \
              STATIC_PATH=/app/static \
              SECRET_KEY=${{secrets.SECRET_KEY}} \
              ALLOWED_HOSTS=${{vars.ALLOWED_HOSTS}} \
              TRUSTED_ORIGINS=${{vars.TRUSTED_ORIGINS}} \
            --registry-server ${{vars.ACR_NAME}}.azurecr.io \
            --user-assigned "$IDENTITY_ID" \
            --registry-identity $IDENTITY_ID \
            --min-replicas 1 \
            --cpu 2.0 \
            --memory 4.0Gi \
            --query properties.configuration.ingress.fqdn

  build_frontend:
    runs-on: "ubuntu-latest"
    # needs: build_backend
    environment: prod-pnh
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ vars.ACR_NAME}}

      - name: Build Docker image for Frontend
        run: |
          docker build -t ${{vars.ACR_NAME}}.azurecr.io/frontend:${{github.ref_name}} \
            --build-arg NEXT_PUBLIC_WAGTAIL_API_URL=${{vars.NEXT_PUBLIC_WAGTAIL_API_URL}} \
            --build-arg NEXT_PUBLIC_API_URL=${{vars.NEXT_PUBLIC_API_URL}} \
            --build-arg WAGTAIL_API_URL=${{vars.WAGTAIL_API_URL}} \
            --build-arg NEXT_PUBLIC_REKENKERN_API_URL=${{vars.NEXT_PUBLIC_REKENKERN_API_URL}} \
            -f ${{github.workspace}}/app/frontend/prod.Dockerfile ${{github.workspace}}/app/frontend

      - name: Push Docker image for Frontend
        run: |
          docker push ${{vars.ACR_NAME}}.azurecr.io/frontend:${{github.ref_name}}
      
      - name: Deploy Frontend to Azure Container App
        run: |
          IDENTITY_ID=$(az identity show \
                  --name ${{vars.IDENTITY}}  \
                  --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
                  --query id \
                  --output tsv)

          az containerapp create \
            --name frontend-prod-app \
            --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
            --environment ${{vars.CONTAINER_APPS_ENV}} \
            --image ${{vars.ACR_NAME}}.azurecr.io/frontend:${{github.ref_name}} \
            --target-port 3000 \
            --ingress external \
            --registry-server ${{vars.ACR_NAME}}.azurecr.io \
            --user-assigned "$IDENTITY_ID" \
            --registry-identity $IDENTITY_ID \
            --min-replicas 1 \
            --cpu 2.0 \
            --memory 4.0Gi \
            --query properties.configuration.ingress.fqdn

  build_nginx:
    runs-on: "ubuntu-latest"
    needs: [build_backend, build_frontend]
    environment: prod-pnh
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ vars.ACR_NAME}}

      - name: Build Docker image for Nginx
        run: |
          docker build -t ${{vars.ACR_NAME}}.azurecr.io/nginx:${{github.ref_name}} -f ${{github.workspace}}/app/nginx/Dockerfile ${{github.workspace}}/app/nginx
      
      - name: Push Docker image for Nginx
        run: |
          docker push ${{vars.ACR_NAME}}.azurecr.io/nginx:${{github.ref_name}}
      
      - name: Deploy Nginx to Azure Container App
        run: |
          IDENTITY_ID=$(az identity show \
                  --name ${{vars.IDENTITY}}  \
                  --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
                  --query id \
                  --output tsv)

          az containerapp create \
            --name tip-pnh \
            --resource-group ${{vars.RESOURCE_GROUP_NAME}} \
            --environment ${{vars.CONTAINER_APPS_ENV}} \
            --image ${{vars.ACR_NAME}}.azurecr.io/nginx:${{github.ref_name}} \
            --target-port 80 \
            --ingress external \
            --registry-server ${{vars.ACR_NAME}}.azurecr.io \
            --user-assigned "$IDENTITY_ID" \
            --registry-identity $IDENTITY_ID \
            --cpu 2.0 \
            --memory 4.0Gi \
            --query properties.configuration.ingress.fqdn
